    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <!-- <link rel="stylesheet" href="http://s.xnimg.cn/rrloan/css/base-all.css?ver=$revxxx$">
    <link rel="stylesheet" href="http://a.xnimg.cn/rrloan/modules/autoloan/css/bootstrap3.css?ver=$revxxx$">
    <link rel="stylesheet" href="http://a.xnimg.cn/rrloan/modules/autoloan/css/layout.css?ver=$revxxx$"> -->

    <!-- Bootstrap core CSS -->
    <link href="${ctx}/static/css/bootstrap.css" rel="stylesheet">
    <!-- <link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet"> -->
    
    <link href="${ctx}/static/css/layout.css" rel="stylesheet">
    <link rel="stylesheet" href="${ctx}/static/css/metisMenu.css">
    <!-- Add custom CSS here -->
    <link href="${ctx}/static/css/sb-admin-2.css" rel="stylesheet">
    <link rel="stylesheet" href="${ctx}/static/font-awesome-sb/css/font-awesome.css">
    <!-- Page Specific CSS -->
    <link rel="stylesheet" href="${ctx}/static/css/morris-0.4.3.min.css">
    <script type="text/javascript">
        var rrloan = {
            user: {
                _rtk: 'b08da1d7'
            },
            env: {
                subdomain: 'platform' ,
                domain: '51fenqi.com'
            }
        };
    </script>